// Code generated by xgen. DO NOT EDIT.

package base

// AircraftOperatorDesignatorType is The identifier of the Aircraft Operator as assigned by ICAO. [FIXM]
// This is the ICAO Operator Code as standardised by ICAO Doc 8585 Manual on Designators for Aircraft Operating Agencies, Aeronautical Authorities and Services.
type AircraftOperatorDesignatorType string

// AircraftOperatorType is Aircraft Operator Identity: Identity of a person, organization or enterprise engaged in or offering to engage in aircraft operation.
type AircraftOperatorType struct {
	DesignatorIcao        string                           `xml:"designatorIcao"`
	Extension             []*AircraftOperatorExtensionType `xml:"extension"`
	OperatingOrganization *PersonOrOrganizationType        `xml:"operatingOrganization"`
}

// PersonOrOrganizationType is The full official name of the Person, State, Organisation, Authority, aircraft operating agency, handling agency etc. [FIXM]
type PersonOrOrganizationType struct {
	Contact          *ContactInformationType              `xml:"contact"`
	Extension        []*PersonOrOrganizationExtensionType `xml:"extension"`
	Identifier       string                               `xml:"identifier"`
	IdentifierDomain string                               `xml:"identifierDomain"`
	Name             string                               `xml:"name"`
}
