// Code generated by xgen. DO NOT EDIT.

package base

// TelecomNetworkTypeType is The Internet is a worldwide, publicly accessible series of interconnected computer networks that transmit data by packet switching using the standard Internet Protocol (IP).
// The usage of this value indicates that a URL will be provided for the linkage property in OnlineContact.
type TelecomNetworkTypeType string

// TextAddressType is Basis for e-mail and street addresses. [FIXM]
type TextAddressType string

// TextCityType is Address city. [FIXM]
type TextCityType string

// TextCountryCodeType is The country code as specified by ISO 3166. [FIXM]
type TextCountryCodeType string

// TextCountryNameType is The country of the physical address for the location or organisation.  Full name, not ISO 3166 abbreviations. [AIXM 5.1]
type TextCountryNameType string

// TextPhoneType is A phone or facsimile number. [AIXM 5.1]
type TextPhoneType string

// ContactInformationType is The official title of the contact.
type ContactInformationType struct {
	Address       *PostalAddressType                 `xml:"address"`
	Extension     []*ContactInformationExtensionType `xml:"extension"`
	Name          string                             `xml:"name"`
	OnlineContact []*OnlineContactType               `xml:"onlineContact"`
	PhoneFax      *TelephoneContactType              `xml:"phoneFax"`
	Title         string                             `xml:"title"`
}

// NetworkChoiceType is Type of telecom network used.
type NetworkChoiceType struct {
	Other string `xml:"other"`
	Type  string `xml:"type"`
}

// OnlineContactType is The Telecom Networks that can be used to address an organisation. [adapted from AIXM]
type OnlineContactType struct {
	Email     string                        `xml:"email"`
	Extension []*OnlineContactExtensionType `xml:"extension"`
	Linkage   string                        `xml:"linkage"`
	Network   *NetworkChoiceType            `xml:"network"`
}

// PostalAddressType is The ZIP or other postal code for the location or organisation.
type PostalAddressType struct {
	AdministrativeArea string                        `xml:"administrativeArea"`
	City               string                        `xml:"city"`
	CountryCode        string                        `xml:"countryCode"`
	CountryName        string                        `xml:"countryName"`
	DeliveryPoint      string                        `xml:"deliveryPoint"`
	Extension          []*PostalAddressExtensionType `xml:"extension"`
	PostalCode         string                        `xml:"postalCode"`
}

// TelephoneContactType is The telephone number by which individuals can speak to the responsible organisation or individual.
type TelephoneContactType struct {
	Extension []*TelephoneContactExtensionType `xml:"extension"`
	Facsimile string                           `xml:"facsimile"`
	Voice     string                           `xml:"voice"`
}
