// Code generated by xgen. DO NOT EDIT.

package base

// ActualTimeOfArrivalExtensionType is A base class for all ActualTimeOfArrival class extensions.
type ActualTimeOfArrivalExtensionType struct {
}

// ActualTimeOfDepartureExtensionType is A base class for all ActualTimeOfDeparture class extensions.
type ActualTimeOfDepartureExtensionType struct {
}

// AerodromeReferenceExtensionType is A base class for all AerodromeReference class extensions.
type AerodromeReferenceExtensionType struct {
}

// AircraftExtensionType is A base class for all Aircraft class extensions.
type AircraftExtensionType struct {
}

// AircraftOperatorExtensionType is A base class for all AircraftOperator class extensions.
type AircraftOperatorExtensionType struct {
}

// AircraftTypeExtensionType is A base class for all AircraftType class extensions.
type AircraftTypeExtensionType struct {
}

// AllPackedInOneExtensionType is A base class for all AllPackedInOne class extensions.
type AllPackedInOneExtensionType struct {
}

// AltitudeInTransitionExtensionType is A base class for all AltitudeInTransition class extensions.
type AltitudeInTransitionExtensionType struct {
}

// ArrivalExtensionType is A base class for all Arrival class extensions.
type ArrivalExtensionType struct {
}

// AtcUnitReferenceExtensionType is A base class for all AtcUnitReference class extensions.
type AtcUnitReferenceExtensionType struct {
}

// BoundaryCrossingExtensionType is A base class for all BoundaryCrossing class extensions.
type BoundaryCrossingExtensionType struct {
}

// CommunicationCapabilitiesExtensionType is A base class for all CommunicationCapabilities class extensions.
type CommunicationCapabilitiesExtensionType struct {
}

// ContactInformationExtensionType is A base class for all ContactInformation class extensions.
type ContactInformationExtensionType struct {
}

// CruiseClimbStartExtensionType is A base class for all CruiseClimbStart class extensions.
type CruiseClimbStartExtensionType struct {
}

// CruisingLevelChangeExtensionType is A base class for all CruisingLevelChange class extensions.
type CruisingLevelChangeExtensionType struct {
}

// CruisingSpeedChangeExtensionType is A base class for all CruisingSpeedChange class extensions.
type CruisingSpeedChangeExtensionType struct {
}

// DangerousGoodsDimensionsExtensionType is A base class for all DangerousGoodsDimensions class extensions.
type DangerousGoodsDimensionsExtensionType struct {
}

// DangerousGoodsExtensionType is A base class for all DangerousGoods class extensions.
type DangerousGoodsExtensionType struct {
}

// DangerousGoodsPackageExtensionType is A base class for all DangerousGoodsPackage class extensions.
type DangerousGoodsPackageExtensionType struct {
}

// DangerousGoodsPackageGroupExtensionType is A base class for all DangerousGoodsPackageGroup class extensions.
type DangerousGoodsPackageGroupExtensionType struct {
}

// DepartureExtensionType is A base class for all Departure class extensions.
type DepartureExtensionType struct {
}

// DesignatedPointExtensionType is A base class for all DesignatedPoint class extensions.
type DesignatedPointExtensionType struct {
}

// DinghiesExtensionType is A base class for all Dinghies class extensions.
type DinghiesExtensionType struct {
}

// EnRouteExtensionType is A base class for all EnRoute class extensions.
type EnRouteExtensionType struct {
}

// EstimatedElapsedTimeExtensionType is A base class for all EstimatedElapsedTime class extensions.
type EstimatedElapsedTimeExtensionType struct {
}

// FlightCapabilitiesExtensionType is A base class for all FlightCapabilities class extensions.
type FlightCapabilitiesExtensionType struct {
}

// FlightConstraintExtensionType is A base class for all FlightConstraint class extensions.
type FlightConstraintExtensionType struct {
}

// FlightEmergencyExtensionType is A base class for all FlightEmergency class extensions.
type FlightEmergencyExtensionType struct {
}

// FlightExtensionType is A base class for all Flight class extensions.
type FlightExtensionType struct {
}

// FlightIdentificationExtensionType is A base class for all FlightIdentification class extensions.
type FlightIdentificationExtensionType struct {
}

// FlightRouteInformationExtensionType is A base class for all FlightRouteInformation class extensions.
type FlightRouteInformationExtensionType struct {
}

// GeographicalPositionExtensionType is A base class for all GeographicalPosition class extensions.
type GeographicalPositionExtensionType struct {
}

// HazardClassExtensionType is A base class for all HazardClass class extensions.
type HazardClassExtensionType struct {
}

// IataFlightDesignatorExtensionType is A base class for all IataFlightDesignator class extensions.
type IataFlightDesignatorExtensionType struct {
}

// LastContactExtensionType is A base class for all LastContact class extensions.
type LastContactExtensionType struct {
}

// LastPositionReportExtensionType is A base class for all LastPositionReport class extensions.
type LastPositionReportExtensionType struct {
}

// LevelConstraintExtensionType is A base class for all LevelConstraint class extensions.
type LevelConstraintExtensionType struct {
}

// MeteorologicalDataExtensionType is A base class for all MeteorologicalData class extensions.
type MeteorologicalDataExtensionType struct {
}

// NavaidExtensionType is A base class for all Navaid class extensions.
type NavaidExtensionType struct {
}

// NavigationCapabilitiesExtensionType is A base class for all NavigationCapabilities class extensions.
type NavigationCapabilitiesExtensionType struct {
}

// OnlineContactExtensionType is A base class for all OnlineContact class extensions.
type OnlineContactExtensionType struct {
}

// PerformanceProfileExtensionType is A base class for all PerformanceProfile class extensions.
type PerformanceProfileExtensionType struct {
}

// PersonOrOrganizationExtensionType is A base class for all PersonOrOrganization class extensions.
type PersonOrOrganizationExtensionType struct {
}

// PlannedDelayExtensionType is A base class for all PlannedDelay class extensions.
type PlannedDelayExtensionType struct {
}

// PostalAddressExtensionType is A base class for all PostalAddress class extensions.
type PostalAddressExtensionType struct {
}

// ProfilePointExtensionType is A base class for all ProfilePoint class extensions.
type ProfilePointExtensionType struct {
}

// RadioactiveMaterialExtensionType is A base class for all RadioactiveMaterial class extensions.
type RadioactiveMaterialExtensionType struct {
}

// RadioCommunicationFailureExtensionType is A base class for all RadioCommunicationFailure class extensions.
type RadioCommunicationFailureExtensionType struct {
}

// ReclearanceInFlightExtensionType is A base class for all ReclearanceInFlight class extensions.
type ReclearanceInFlightExtensionType struct {
}

// RelativePointExtensionType is A base class for all RelativePoint class extensions.
type RelativePointExtensionType struct {
}

// RestrictionReferenceExtensionType is A base class for all RestrictionReference class extensions.
type RestrictionReferenceExtensionType struct {
}

// RouteChangeExtensionType is A base class for all RouteChange class extensions.
type RouteChangeExtensionType struct {
}

// RouteTrajectoryConstraintExtensionType is A base class for all RouteTrajectoryConstraint class extensions.
type RouteTrajectoryConstraintExtensionType struct {
}

// RouteTrajectoryElementExtensionType is A base class for all RouteTrajectoryElement class extensions.
type RouteTrajectoryElementExtensionType struct {
}

// RouteTrajectoryGroupContainerExtensionType is A base class for all RouteTrajectoryGroupContainer class extensions.
type RouteTrajectoryGroupContainerExtensionType struct {
}

// RouteTrajectoryGroupExtensionType is A base class for all RouteTrajectoryGroup class extensions.
type RouteTrajectoryGroupExtensionType struct {
}

// ShippingInformationExtensionType is A base class for all ShippingInformation class extensions.
type ShippingInformationExtensionType struct {
}

// SidStarReferenceExtensionType is A base class for all SidStarReference class extensions.
type SidStarReferenceExtensionType struct {
}

// SpeedConstraintExtensionType is A base class for all SpeedConstraint class extensions.
type SpeedConstraintExtensionType struct {
}

// SpeedScheduleExtensionType is A base class for all SpeedSchedule class extensions.
type SpeedScheduleExtensionType struct {
}

// SupplementaryInformationExtensionType is A base class for all SupplementaryInformation class extensions.
type SupplementaryInformationExtensionType struct {
}

// SurveillanceCapabilitiesExtensionType is A base class for all SurveillanceCapabilities class extensions.
type SurveillanceCapabilitiesExtensionType struct {
}

// SurvivalCapabilitiesExtensionType is A base class for all SurvivalCapabilities class extensions.
type SurvivalCapabilitiesExtensionType struct {
}

// TelephoneContactExtensionType is A base class for all TelephoneContact class extensions.
type TelephoneContactExtensionType struct {
}

// TimeConstraintExtensionType is A base class for all TimeConstraint class extensions.
type TimeConstraintExtensionType struct {
}

// TimeRangeExtensionType is A base class for all TimeRange class extensions.
type TimeRangeExtensionType struct {
}

// TrajectoryPoint4DExtensionType is A base class for all TrajectoryPoint4D class extensions.
type TrajectoryPoint4DExtensionType struct {
}

// TrajectoryPointPropertyExtensionType is A base class for all TrajectoryPointProperty class extensions.
type TrajectoryPointPropertyExtensionType struct {
}

// TrajectoryPointReferenceExtensionType is A base class for all TrajectoryPointReference class extensions.
type TrajectoryPointReferenceExtensionType struct {
}

// TrueAirspeedRangeExtensionType is A base class for all TrueAirspeedRange class extensions.
type TrueAirspeedRangeExtensionType struct {
}

// VerticalRangeExtensionType is A base class for all VerticalRange class extensions.
type VerticalRangeExtensionType struct {
}
