// Code generated by xgen. DO NOT EDIT.

package base

// AltitudeSourceType is This value indicates that the source is the Global Navigation Satellite System.
type AltitudeSourceType string

// MeasureType is The result from performing the act or process of ascertaining the value of a characteristic of some entity. [ISO 19103, chapter 6.5.7.2]
type MeasureType float64

// RestrictedAngleType is Helper class for restrictions on Angle
type RestrictedAngleType float64

// RestrictedMeasureType is Helper class for restrictions on measures.  [FIXM]
type RestrictedMeasureType float64

// RestrictedSpeedType ...
type RestrictedSpeedType float64

// RestrictedVerticalDistanceType is Helper class for restrictions on fractionDigits
type RestrictedVerticalDistanceType float64

// SpeedType is The value of a speed. [AIXM 5.1]
type SpeedType float64

// VerticalDistanceType is A vertical distance value. [AIXM 5.1]
type VerticalDistanceType float64

// VerticalReferenceType is The distance measured from the WGS84 ellipsoid. [AIXM 5.1]
type VerticalReferenceType string

// ZeroBearingTypeType is This value indicates that the direction is relative to True North.
type ZeroBearingTypeType string

// AltitudeType is The vertical distance of a level, a point or an object considered as a point, measured from mean sea level (MSL). [ICAO Doc 4444]
type AltitudeType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// AltitudeWithSourceType is An altitude with a specified source. [FIXM]
type AltitudeWithSourceType struct {
	SourceAttr string `xml:"source,attr"`
	*AltitudeType
}

// AngleType is The amount of rotation needed to bring one line or plane into coincidence with another, generally measured in radians or degrees. [ISO 19103, chapter 6.5.7.9]
type AngleType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// BearingType is A data type used to represent direction in the coordinate reference system. [ISO 19107, chapter 6.3.12.1]
//
// The value of a bearing indication (at a given point) is measured as the angle between the bearing and either True North or Magnetic North. The angle is measured clockwise from 0 degrees up to and including 360 degrees. The value can also be a VOR radial.  [AIXM 5.1]
type BearingType struct {
	ZeroBearingTypeAttr string `xml:"zeroBearingType,attr"`
	*AngleType
}

// DistanceType is A type for returning the separation between two points. [ISO 19103, chapter 6.5.7.7]
type DistanceType struct {
	*LengthType
}

// FlightLevelType is A surface of constant atmospheric pressure which is related to a specific pressure datum, 1 013.2 hectopascals (hPa), and is separated from other such surfaces by specific pressure intervals. [ICAO Doc 4444]
type FlightLevelType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// FrequencyType is The frequency value of a navigation system. [AIXM 5.1]
type FrequencyType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// GroundSpeedType is The speed of an aircraft relative to the surface of the earth. [ICAO Doc 9426]
type GroundSpeedType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// HeightType is The vertical distance of a level, a point or an object considered as a point, measured from a specified datum. [ICAO Doc 4444]
type HeightType struct {
	RefAttr string  `xml:"ref,attr"`
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// IndicatedAirspeedType is The uncorrected reading on the airspeed indicator. [ICAO Doc 9426]
type IndicatedAirspeedType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// LengthType is The measure of distance as an integral, for example the length of curve, the perimeter of a polygon as the length of the boundary. [ISO 19103, chapter 6.5.7.6]
type LengthType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// MassType is The value of a mass. [AIXM 5.1]
type MassType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// PressureType is The value of a pressure. [AIXM 5.1]
type PressureType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// TemperatureType is The value of a temperature. [AIXM 5.1]
type TemperatureType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// TrueAirspeedType is The speed of the aeroplane relative to undisturbed air. [ICAO Doc 9713]
type TrueAirspeedType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// VerticalRateType is An expression of an aircraft's vertical rate of change. [FIXM]
type VerticalRateType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// VolumeType is The measure of the physical space of any 3-D geometric object. [ISO 19103, chapter 6.5.7.15]
type VolumeType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// WeightType is The value of a weight. [AIXM 5.1]
type WeightType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}

// WindDirectionType is Direction from which the wind blows. [International Meteorological Vocabulary, WMO]
type WindDirectionType struct {
	*AngleType
}

// WindSpeedType is The speed of wind. [FIXM]
type WindSpeedType struct {
	UomAttr string  `xml:"uom,attr"`
	Value   float64 `xml:",chardata"`
}
