// Code generated by xgen. DO NOT EDIT.

package base

// AircraftIdentificationType is A group of letters, figures or a combination thereof which is either identical to, or the coded equivalent of, the aircraft call sign to be used in air-ground communications, and which is used to identify the aircraft in ground-ground air traffic services communications. [ICAO Doc 4444]
type AircraftIdentificationType string

// AircraftTypeDesignatorType is A group of alphanumeric characters used to identify, in an abbreviated form, a type of aircraft. [ICAO Doc 9426]
//
// Approved aircraft type designators are defined in ICAO Doc. 8643 - Aircraft Type Designators. [FIXM]
type AircraftTypeDesignatorType string

// AirportSlotIdentificationType is The identifier of the scheduled time of arrival or departure available for allocation by, or as allocated by, a coordinator for an aircraft movement on a specific date at a coordinated airport. [adapted from IATA Worldwide Scheduling Guidelines, 21st Edition]
type AirportSlotIdentificationType string

// CharacterStringType is A sequence of characters [specialised from ISO19103, chapter 6.5.2.7].
//
// In FIXM, the maximum length of a CharacterString is set to 4096 characters. [FIXM]
type CharacterStringType string

// CountType is Represents non-negative integer counts of objects.
type CountType int

// CountPositiveType is Represents positive integer counts of objects.
type CountPositiveType int

// DateTimeUtcType is Describes instances identified by the combination of a date and a time expressed in Coordinated Universal Time (UTC) and restricted to whole second precision.  [FIXM]
type DateTimeUtcType string

// DateTimeUtcHighPrecisionType is Describes instances identified by the combination of a date and a time expressed in Coordinated Universal Time (UTC).  [FIXM]
type DateTimeUtcHighPrecisionType string

// DateUtcType is Describes a date represented in Coordinated Universal Time (UTC). [FIXM]
type DateUtcType string

// DecimalIndexType is Generic decimal fraction expressed to tenths, used as scaling or comparison factor. [FIXM]
type DecimalIndexType float64

// DurationType is Length or distance in the temporal dimension. [ISO 19108, chapter 5.2.3.7]
//
// Duration has no reference to start or stop times.
type DurationType string

// HypertextReferenceType is This class provides an optional mechanism enabling FIXM aeronautical fields to be supplemented with references to AIXM features.  Uses of this field should be considered functionally equivalent to the xlink:href field used in AIXM to reference features.  [FIXM]
type HypertextReferenceType string

// ModeACodeType is Mode A SSR code. [FIXM]
type ModeACodeType string

// NamespaceDomainType is An operating agency can be identified by its three-letter Operating Agency Designator (ICAO Doc. 8585).
type NamespaceDomainType string

// NamespaceIdentifierType is The namespace chosen by the GUFI originator.  Used to reduce the likelihood of GUFI collisions and provide traceability as to which entity generated a particular GUFI.
type NamespaceIdentifierType string

// RestrictedUniversallyUniqueIdentifierType is Helper type for restrictions on UniversallyUniqueIdentifier
type RestrictedUniversallyUniqueIdentifierType string

// TextNameType is The official name of a State, an aerodrome, a unit, etc... [AIXM 5.1]
type TextNameType string

// GloballyUniqueFlightIdentifierType is An immutable identifier associated with a flight that allows all eligible members of the ATM community to unambiguously refer to information pertaining to the flight.
type GloballyUniqueFlightIdentifierType struct {
	CreationTimeAttr        string `xml:"creationTime,attr"`
	NamespaceDomainAttr     string `xml:"namespaceDomain,attr"`
	NamespaceIdentifierAttr string `xml:"namespaceIdentifier,attr"`
	*UniversallyUniqueIdentifierType
}

// RestrictionReferenceType is Used to identify the type of published restriction being referenced. [FIXM]
type RestrictionReferenceType struct {
	HrefAttr              string                               `xml:"href,attr,omitempty"`
	Extension             []*RestrictionReferenceExtensionType `xml:"extension"`
	RestrictionIdentifier string                               `xml:"restrictionIdentifier"`
	RestrictionType       string                               `xml:"restrictionType"`
}

// UniversallyUniqueIdentifierType is A 128-bit number used, with a high probability, to uniquely identify information in computer systems. [FIXM]
type UniversallyUniqueIdentifierType struct {
	CodeSpaceAttr string `xml:"codeSpace,attr"`
	Value         string `xml:",chardata"`
}
